name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Git Semantic Version
      id: version_id
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        major_pattern: "MAJOR:"
        minor_pattern: "MINOR:"
        format: "${major}.${minor}.${increment}"
            
    - name: Docker login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
     
    - name: Build docker image
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        NEW_VERSION: ${{steps.version_id.outputs.version}}
      run: |
        docker build -t $DOCKERHUB_USER/docker-graphql:$NEW_VERSION .
        docker build -t $DOCKERHUB_USER/docker-graphql:latest .
    - name: Push docker image
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        NEW_VERSION: ${{steps.version_id.outputs.version}}
      run: |
        docker push $DOCKERHUB_USER/docker-graphql:$NEW_VERSION
        docker push $DOCKERHUB_USER/docker-graphql:latest

