name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0
    - name: Docker login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        echo "Login ok"
    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
