name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code from repository
      uses: actions/checkout@v4
      with: 
        fetch-depth: 0

    - name: Git Semantic Version
      uses: PaulHatch/semantic-version@v4.0.3
      with:
        branch: "master"
        major_pattern: "major:"
        minor_pattern: "minor:"
        format: "${major}.${minor}.${patch}-prerelease${increment}"
      id: version
        
            
    - name: Docker login
      env:
        DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
        DOCKERHUB_PASSWORD: ${{secrets.DOCKERHUB_PASSWORD}}
        NEW_VERSION: ${{steps.version.output.version}}
      run: |
        echo "Iniciando login"
        docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASSWORD
        echo ${{steps.version.output.version}}

        
    # - name: Build docker image
    #   env:
    #     DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
    #   run: |
    #     docker build -t $DOCKERHUB_USER/docker-graphql:0.0.2 .
    #     docker build -t $DOCKERHUB_USER/docker-graphql:latest .
    # - name: Push docker image
    #   env:
    #     DOCKERHUB_USER: ${{secrets.DOCKERHUB_USER}}
    #   run: |
    #     docker push $DOCKERHUB_USER/docker-graphql:0.0.2
    #     docker push $DOCKERHUB_USER/docker-graphql:latest




    
    # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
